supabase/supabase-swift

Package.resolved
Package.swift
Sources/Supabase/Supabase.swift
Tests/LinuxMain.swift
Tests/SupabaseTests/SupabaseTests.swift
Tests/SupabaseTests/XCTestManifests.swift

Feature adding missing `PostgrestClient` to `SupabaseClient`.

Add PostgrestClient to Supabase

---

README.md
Sources/Supabase/Supabase.swift
Sources/Supabase/SupabaseClient.swift
Tests/SupabaseTests/SupabaseTests.swift

Adds documentation for the main behaviors of the `SuperbaseClient` Object. Also adds usage, installation and other documentation to the README. I'll add more docs like that soon.
There's little documentation.
There's docs 🎉

Start adding documentation

---

Sources/Supabase/SupabaseClient.swift

Set the realtime client public, like auth, storage and database.
FIX issue RealtimeClient is private #9.
Bug fix or feature
#9 
Give access to the realtime client.

Change the visibility of the realtime client.

---

Package.swift
README.md

Hey 👋
I updated the README to match the current implementation and I added the `platforms` field in `Package.swift` because without it I couldn't import `Supabase` inside the iOS project.
Have a nice day ☀️,
Cosmin

README update & added "platforms" in Package.swift 

---

Package.resolved
Package.swift
Sources/Supabase/SupabaseClient.swift

Refresh session before calling into Postgrest

---

Package.resolved
Package.swift
Sources/Supabase/SupabaseClient.swift

Implement `PostgrestHTTPClient` and `StorageHTTPClient` for adapting URLRequest before its sent.
Depends on:
* https://github.com/supabase-community/postgrest-swift/pull/33
* https://github.com/supabase-community/storage-swift/pull/6

Implement HTTP Client protocols for sub packages

---

Package.resolved
Package.swift

Update dependency branch name swift-storage to 'main'

update dependency branch name

---

README.md

Fixed a small issue of the previous PR that updated the `README` file.
N/A
N/A
N/A

Fix small error in README instructions

---

README.md

Docs update.
The current example provided in the README is incorrect. 
The change fixes the example provided
This is a similar change that was made in the last pull requests but it was not taken into consideration on the social login

Fix small error in README Social Login

---

README.md

Updated README
The example currently produces a compiler error in XCode. 
The example should work as the original authors intended. 
A full explanation can be found in [this issue](https://github.com/supabase-community/supabase-swift/issues/70)

fixed CRUD implementation

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/UserManagement/AppView.swift
Examples/UserManagement/ProfileView.swift
Sources/GoTrue/GoTrueClient.swift
Sources/GoTrue/Internal/EventEmitter.swift
Sources/Supabase/SupabaseClient.swift
Tests/GoTrueTests/GoTrueClientTests.swift

feat: rename onAuthStateChange to authStateChanges and add event key to posted notification

---

Sources/PostgREST/PostgrestTransformBuilder.swift

Close https://github.com/supabase-community/postgrest-swift/issues/54

feat(postgrest): rename foreignTable to referencedTable

---

Sources/_Helpers/Version.swift

chore: bump version to 1.1.0

---

.github/workflows/ci.yml

chore: add CI job for building library evolution

---

.github/workflows/ci.yml
.swiftpm/xcode/xcshareddata/xcschemes/Functions.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/PostgREST.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/Realtime.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/Storage.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/Supabase.xcscheme
Examples/Examples.xcodeproj/project.pbxproj
Examples/Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
Examples/Examples/ActionState.swift
Examples/Examples/Auth/AuthController.swift
Examples/Examples/Auth/AuthView.swift
Examples/Examples/Auth/AuthWithEmailAndPassword.swift
Examples/Examples/Auth/AuthWithMagicLink.swift
Examples/Examples/Auth/SignInWithApple.swift
Examples/Examples/AuthView.swift
Examples/Examples/Contants.swift
Examples/Examples/Debug.swift
Examples/Examples/ErrorText.swift
Examples/Examples/Examples.entitlements
Examples/Examples/ExamplesApp.swift
Examples/Examples/HomeView.swift
Examples/Examples/Info.plist
Examples/Examples/MFAFlow.swift
Examples/Examples/RootView.swift
Examples/Examples/TodoListView.swift
Examples/Examples/_Secrets.swift
Makefile
Sources/Auth/Types.swift

docs: refactor Examples project

---

Sources/_Helpers/Version.swift

Bump version to 2.1.0

---

Sources/Auth/Internal/Helpers.swift
Tests/AuthTests/ExtractParamsTests.swift

test: add test for extractParams function

---

Sources/Supabase/SupabaseClient.swift
Tests/SupabaseTests/SupabaseClientTests.swift

fix: add init with default options param

---

.github/workflows/ci.yml

ci: update runner to macos-14

---

Sources/_Helpers/SupabaseLogger.swift

chore: fix package for building on Swift 5.8

---

Sources/Auth/AuthClient.swift
Tests/AuthTests/AuthClientTests.swift

docs: add documentation comments to onAuthStateChange

---

.github/workflows/ci.yml
Package.resolved
Package.swift

chore: add Swift 5.10 to CI

---

Sources/Auth/AuthClient.swift
Sources/Auth/Types.swift
Tests/AuthTests/__Snapshots__/RequestsTests/testSignInWithOTPUsingPhone.1.txt

Close https://github.com/supabase-community/supabase-swift/issues/127

feat(auth): add whatsapp channel option to signInWithOTP

---

.github/workflows/ci.yml
Makefile

ci: cache builds for improve build times

---

Sources/Auth/AuthClient.swift
Sources/Auth/Internal/CodeVerifierStorage.swift
Tests/AuthTests/Mocks/Mocks.swift
Tests/AuthTests/RequestsTests.swift

refactor(auth): in memory code verifier storage

---

.github/workflows/conventional-commits-lint.js
.github/workflows/conventional-commits.yml

ci: add conventional commits lint

---

Sources/PostgREST/PostgrestBuilder.swift

#325 was not the only race condition, this PR fixes another one that could happen between updating the request object and calling the http fetch method.

fix(postgrest): race condition when executing request

---

README.md

chore: update spi badges on README

---

.github/workflows/conventional-commits-lint.js

Update commit lint behavior to allow breaking change PRs

chore: commit lint allow breaking change

---

Package.swift
Sources/PostgREST/PostgrestFilterBuilder.swift
Sources/PostgREST/Types.swift
Tests/IntegrationTests/Potsgrest/PostgresTransformsTests.swift
Tests/IntegrationTests/Potsgrest/PostgrestBasicTests.swift
Tests/IntegrationTests/Potsgrest/PostgrestFilterTests.swift
Tests/IntegrationTests/Potsgrest/PostgrestResourceEmbeddingTests.swift

Implements integration tests for Postgrest

test(postgrest): integration tests

---

Package.swift
Sources/Supabase/SupabaseClient.swift
supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved

* Update outdated dependencies
* Sort dependencies in Package.swift alphabetically
* Replace compiler directive condition `#if !os(Windows) && !os(Linux)` with the proper `condition` param when adding a dependency to a target see https://github.com/supabase/supabase-swift/pull/388/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR54

chore: update dependencies and fix some build warnings

---

Package.resolved
Package.swift
Sources/Auth/Internal/Keychain.swift
Sources/Auth/Storage/KeychainLocalStorage.swift

refactor: implement Keychain and drop KeychainAccess dependency

---

Makefile
supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved

chore: fix Makefile

---

Sources/_Helpers/SupabaseLogger.swift
Sources/_Helpers/TaskLocalHelpers.swift

refactor: add @_unsafeInheritExecutor and @inlinable to trace method

---

Sources/Supabase/Types.swift

fix(auth): missing autoRefreshToken param in initializer

---

Examples/Examples/AnyJSONView.swift
Examples/UserManagement/AppView.swift
Examples/UserManagement/ProfileView.swift
Sources/Realtime/V2/CallbackManager.swift
Sources/Realtime/V2/RealtimeChannelV2.swift
Sources/Realtime/V2/RealtimeMessageV2.swift
Sources/Realtime/V2/WebSocketClient.swift
Tests/RealtimeTests/RealtimeMessageV2Tests.swift
Tests/RealtimeTests/RealtimeTests.swift

General improvements on realtime package.
- Adds documentation comments
- Adds tests

refactor(realtime): general realtime improvements

---

Sources/Supabase/SupabaseClient.swift

Bug fix
When user sign out, subscribed realtime channels maintain the old access token
When user sign out, revert the access token to the API key for all subscribed channels

fix(realtime): revert realtime token to apikey on user sign out

---

Sources/Realtime/V2/RealtimeChannelV2.swift
Sources/Realtime/V2/RealtimeClientV2.swift
Sources/Realtime/V2/RealtimeJoinConfig.swift
Tests/RealtimeTests/RealtimeTests.swift
Tests/RealtimeTests/_PushTests.swift

fix: Add private topic to Realtime

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/Examples/Profile/ProfileView.swift
Examples/Examples/Profile/UpdateProfileView.swift
Tests/IntegrationTests/AuthClientIntegrationTests.swift

Add integration test for updating user after anonymous sign in (i.e. link identity)

test(auth): update user after anonymous sign in

---

Sources/Helpers/EventEmitter.swift
Sources/Realtime/V2/RealtimeChannelV2.swift
Tests/IntegrationTests/RealtimeIntegrationTests.swift
Tests/RealtimeTests/MockWebSocketClient.swift
Tests/RealtimeTests/RealtimeTests.swift

Fix `MockWebSocketClient`, buffer sent messages/status if no client subscribed yet.

test(realtime): fix MockWebSocketClient

---

Sources/TestHelpers/HTTPClientMock.swift
Tests/AuthTests/SessionManagerTests.swift
Tests/FunctionsTests/FunctionsClientTests.swift

test: fix failing tests

---

Sources/Auth/Types.swift

Fix adding missing auth providers

fix(auth): add missing figma, kakao, linkedin_oidc, slack_oidc, zoom, and fly providers

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/Examples/Auth/AuthController.swift
Examples/Examples/Auth/AuthView.swift
Examples/Examples/Auth/SignInWithPhone.swift
Examples/supabase/config.toml
Supabase.xcworkspace/xcshareddata/swiftpm/Package.resolved

chore(docs): add phone sign in example

---

Supabase.xcworkspace/xcshareddata/swiftpm/Package.resolved
Tests/IntegrationTests/AuthClientIntegrationTests.swift

test(auth): add integration test for signOut

---

.github/workflows/ci.yml
Sources/Helpers/AnyJSON/AnyJSON+Codable.swift
Tests/HelpersTests/AnyJSONTests.swift

refactor: AnyJSON type

---

Sources/Storage/BucketOptions.swift
Sources/Storage/StorageBucketApi.swift
Sources/Storage/StorageFileApi.swift
Sources/Storage/TransformOptions.swift
Sources/Storage/Types.swift

docs(storage): improve docs for storage methods

---

Sources/Realtime/RealtimeChannel+AsyncAwait.swift

Fixes https://github.com/supabase/supabase-swift/issues/606
`swift build` fails on macOS 13
Behavior should be unchanged.
Note the two `eraseToStream()` implementations at https://github.com/pointfreeco/swift-concurrency-extras/blob/e96a8a76fdccf12ab4b087cdf2d867dd74cd065c/Sources/ConcurrencyExtras/AsyncStream.swift#L103. The macOS swift compiler seem to not be clever enough to pick one, so this PR sidesteps the problem by just doing the same thing as `eraseToStream()` inline.

Work around type ambiguity in macOS 13 swift build

---

Examples/Examples/Auth/SignInWithApple.swift

Update Sign in with Apple example by showing how to store the user's full name in the database.

docs(examples): update sign in with apple example to save user's full name

---

Examples/Examples/Info.plist

chore(examples): add reversed client id as URL scheme

---

.github/workflows/ci.yml

ci: disable library evolution job

---

docs/migrations/RealtimeV2 Migration Guide.md

Close https://github.com/supabase/supabase-swift/issues/687

docs: fix Update RealtimeV2 Migration Guide.md

---

README.md

chore: fix min supported Xcode version

---

.github/workflows/release.yml

chore: fix deprecated action for release

---

.github/workflows/ci.yml
.github/workflows/conventional-commits.yml

small change for actions permissions

ci: explicit permissions and remove pull_request_target

---

.github/workflows/ci.yml

ci: bump xcode version to 16.3

---

.github/workflows/ci.yml
.spi.yml

docs: instruct spi to build docs

---

.github/workflows/release.yml

chore(ci): fix semantic-release to use github app

---

.github/dependabot.yml

chore: remove commit prefix from dependabot
