supabase/supabase-swift

Package.swift
There are some errors on registration so it would be great if we update GoTrue to the latest version. In the latest version this problem seems to be fixed.
=> Update GoTrue to the latest version

Sources/Supabase/SupabaseClient.swift
Ignore `SessionNotFound` error on "refresh session if needed"
`gotrue-swift` throws and `SessionNotFound` when session is not found.
Supabase supports tables without RLS and requests to public tables without an auth session. Old behaviour prevents user to request data from database without having a valid auth session.
New behaviour will continue running the request with the application API key.
Populate an empty Supabase project with the `Countries` quick start script and request data from that table:
```
let countryQuery = client.database.from("countries").select()
let countryResponse = try await countryQuery.execute()
if let data = try? countryResponse.decoded(to: [Country].self) {
countries = data
}
```
=> Ignore error on refreshing current session

Package.swift, Sources/Supabase/SupabaseClient.swift
Fixes build errors mentioned in issue #52 by:
- Updating Package file
- Updating `SupabaseClient.swift`
Fails to build due to breaking changes in `postgrest-swift`
Now builds and runs as expected
Glad to help!
=> Fixed buid errors - #52

Package.swift, Sources/Supabase/SupabaseClient.swift, Tests/SupabaseTests/SupabaseClientTests.swift
Fixes #58 
A wrong functions URL was used for initializing the `FunctionsClient`.
Check if the Supabase URL contains `supabase.co` or `supabase.in`, and create the functions URL based on it.
=> Fix functions URL

README.md
Added Basic Login implementation and some Social Login Implementation for Swift using UIKit
Update to the ReadMe
The current Read Me does not include examples for login and social login
Added examples for the login and social logins
I believe this would be very helpful for people who want to get started with Supabase for iOS Projects.
=> Updated Readme with Login/Signup Implementation

README.md
Added in Insert and Select Queries for Supabase Swift
Added documentation for Insert and Select Queries
Current documentation does not show basic CRUD functionalities. It's only available as tests on Postgrest-Swift repo, which not everyone might find easily.
Added documentation for Insert and Select Queries
I'll add in Update and Delete functionality once I've used them.
=> Update ReadMe with Insert and Select Queries

README.md
- This PR adds a 'Contents' section to the README file.
- The contents section acts as an index with links to the respective sections.
- This should allow users to quickly jump to specific sections of the documentation as required.
- Currently the documentation does not have a contents section providing an overview of the docs.
- As the documentation grows, navigating it could become tedious.
- The changes allow to jump between sections through the links.
NA
=> Adding an index to docs for ease of access

Examples/Examples/TodoListView.swift, Sources/Supabase/Deprecations.swift, Sources/Supabase/SupabaseClient.swift, Sources/Supabase/Types.swift, supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved
Close #69 
* Add a new `SupabaseClientOptions` type based on the one from the official `supabase-js`.
* Add a new initializer that uses this option.
* Deprecate the old initializer.
=> Add support for customizing client initialization

README.md
This PR introduces documentation for:
- Updating data
- Deleting data
- Using Postgres (RPC) functions
- A potenial common mistake you can make while developing your models
Missing documentation for some CRUD operations
N/A
When originally working with supabase-swift, I found some of the API from supabase-js to not be 1:1 and I found myself spendign a lot of time digging through issues or the supabase discord to see if I could find info, so I just wanted to add some of the operations I had to search for and some of the things I spent a lot of time trying to figure out so any future users of the library can hopefully spend a little less time trying to get their grips with everything!
=> Add further CRUD and RPC documentation

Package.resolved, Sources/Supabase/SupabaseClient.swift, Tests/SupabaseTests/SupabaseClientTests.swift
This PR solves the issue #87, which adds the `Authorization` header to the client so that the user can access the storage module with a `SupabaseClient` 
Currently, it is imposible to access the storage module without manually initializing a `SupabaseStorageClient` and setting each header.
Now, it will be possible to.
=> Add missing headers

Package.resolved, Sources/Supabase/SupabaseClient.swift, Tests/SupabaseTests/SupabaseClientTests.swift
feature
Invoke functions with `/functions/v1` path prefix allowing us to support custom domains and vanity domains for edge functions
=> feat: edge functions support for custom domains and vanity domains

.swiftpm/xcode/xcshareddata/xcschemes/Supabase-Package.xcscheme, Examples/Examples.xcodeproj/project.pbxproj, Examples/Examples/AuthView.swift, Examples/Examples/HomeView.swift, Examples/Examples/Info.plist, Examples/Examples/MFAFlow.swift, Examples/Examples/RootView.swift, Examples/ProductSample/Data/AuthenticationRepository.swift, Package.resolved, Package.swift, Sources/GoTrue/GoTrueClient.swift, Sources/GoTrue/GoTrueMFA.swift, Sources/GoTrue/Internal/APIClient.swift, Sources/GoTrue/Internal/CodeVerifierStorage.swift, Sources/GoTrue/Internal/Dependencies.swift, Sources/GoTrue/Internal/EventEmitter.swift, Sources/GoTrue/Internal/SessionManager.swift, Sources/GoTrue/Internal/SessionStorage.swift, Sources/GoTrue/Types.swift, Sources/_Helpers/AsyncStream.swift, Sources/_Helpers/Task.swift, Tests/GoTrueTests/GoTrueClientTests.swift, Tests/GoTrueTests/RequestsTests.swift, Tests/GoTrueTests/SessionManagerTests.swift, supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> Add MFA Support to GoTrue

.swiftpm/xcode/xcshareddata/xcschemes/Supabase.xcscheme, Examples/Examples/AuthView.swift, Sources/GoTrue/GoTrueClient.swift, Sources/GoTrue/GoTrueMFA.swift, Sources/GoTrue/Internal/APIClient.swift, Sources/GoTrue/Internal/EventEmitter.swift, Sources/PostgREST/PostgrestBuilder.swift, Sources/PostgREST/PostgrestClient.swift, Sources/PostgREST/PostgrestFilterBuilder.swift, Sources/PostgREST/PostgrestQueryBuilder.swift, Sources/PostgREST/PostgrestRpcBuilder.swift, Sources/PostgREST/PostgrestTransformBuilder.swift, Sources/PostgREST/Types.swift, Sources/Realtime/RealtimeChannel.swift, Sources/Realtime/RealtimeClient.swift, Sources/Storage/StorageApi.swift, Sources/Storage/StorageBucketApi.swift, Sources/Storage/StorageFileApi.swift, Sources/Supabase/SupabaseClient.swift, Sources/_Helpers/Request.swift, Supabase.xctestplan, Tests/GoTrueTests/GoTrueClientTests.swift, Tests/GoTrueTests/Mocks/Mocks.swift, Tests/GoTrueTests/RequestsTests.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, supabase-swift.xcworkspace/contents.xcworkspacedata
Refactor
Some sub-packages implement their logic for building a URLRequest.
All sub-packages, GoTrue, Supabase, and PostgREST, share the same logic for transforming a `Request` into a `URLRequest` for later execution.
=> refactor: share request logic between sub-packages

Sources/GoTrue/GoTrueClient.swift, Sources/GoTrue/Types.swift
=> refactor: Separate `OTPType` into mobile and email

Sources/PostgREST/PostgrestClient.swift, Sources/PostgREST/PostgrestFilterBuilder.swift, Sources/PostgREST/PostgrestQueryBuilder.swift, Sources/PostgREST/PostgrestTransformBuilder.swift, Tests/PostgRESTIntegrationTests/IntegrationTests.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift
=> refactor: rename some PostgREST function parameters

Sources/Functions/FunctionsClient.swift, Sources/PostgREST/PostgrestFilterBuilder.swift, Tests/FunctionsTests/FunctionsClientTests.swift
=> refactor: rename functions method parameters

Sources/Realtime/RealtimeChannel.swift, Sources/Realtime/RealtimeClient.swift
=> refactor: realtime

Sources/Storage/StorageBucketApi.swift, Sources/Storage/StorageFileApi.swift, Sources/Storage/SupabaseStorage.swift, Tests/StorageTests/StorageClientIntegrationTests.swift, Tests/StorageTests/SupabaseStorageClient+Test.swift, Tests/StorageTests/SupabaseStorageTests.swift
=> refactor: omit some method parameters in storage

.swiftpm/xcode/xcshareddata/xcschemes/PostgREST.xcscheme, Sources/GoTrue/Types.swift, Sources/PostgREST/PostgrestClient.swift, Sources/PostgREST/PostgrestRpcBuilder.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.call-rpc-with-filter.txt
Feature, close #149
Documentation update: https://github.com/supabase/supabase/pull/18682/commits/1e7fe57af75e7be96a5df7e43ed64b013a7c8f23
Can't call a filter such as `eq` after `rpc`.
Make `rpc` method returns a `PostgrestFilterBuilder`, so all filters can be appended to the call.
=> feat: add filter to RPC call

Sources/Functions/Types.swift, Tests/FunctionsTests/FunctionInvokeOptionsTests.swift
Bug fix
`FunctionInvokeOptions` overrides the specified `Content-Type` header value to `application/octet-stream` when body is of type `Data`.
If a custom `content-type` is passed to the initializer, keep it.
Same fix as https://github.com/supabase-community/functions-swift/pull/6, but in monorepo
=> fix(functions): functions overrides headers

.github/workflows/ci.yml, Examples/Examples.xcodeproj/project.pbxproj, Examples/UserManagement/AvatarImage.swift, Examples/UserManagement/Models.swift, Examples/UserManagement/ProfileView.swift, Makefile, Sources/Storage/StorageFileApi.swift, Tests/StorageTests/StorageClientIntegrationTests.swift
=> docs: add Avatar Image to UserManagement example

Examples/Examples.xcodeproj/project.pbxproj, Examples/RealtimeSample/ContentView.swift, Examples/RealtimeSample/RealtimeSampleApp.swift, Examples/UserManagement/Supabase.swift, Sources/Supabase/SupabaseClient.swift, Tests/SupabaseTests/SupabaseClientTests.swift
=> docs: fix Realtime example

Sources/GoTrue/GoTrueError.swift
Fixes a small bug when decoding API errors in the GoTrue package.
The current `keyDecodingStrategy` used by the GoTrue package already decodes from snake case to camel case, however coding keys were explicitly set, leading to an error message with missing information. I came across this when trying out Supabase for the first time and receiving an error about an unconfirmed email address, it was impossible to debug this without running a network proxy and inspecting the response.
Removes codingKeys from `GoTrueError.APIError` as this is covered already by `keyDecodingStrategy` and was causing issues.
=> Fix error decoding

Sources/GoTrue/GoTrueClient.swift, Sources/GoTrue/Types.swift, Tests/GoTrueTests/RequestsTests.swift, Tests/GoTrueTests/__Snapshots__/RequestsTests/testSignOutWithLocalScope.1.txt, Tests/GoTrueTests/__Snapshots__/RequestsTests/testSignOutWithOthersScope.1.txt
Adds the `scope` parameter to the signOut method which can be used to control which sessions should be signed out of the account.
Calling `signOut()` with no scope specified signs out all sessions, revoking all refresh tokens for the user.
This behaviour is maintained with the default scope parameter `.global`.
Adds scope parameter to `signOut()`.
https://github.com/supabase/gotrue/pull/1112
https://github.com/supabase/gotrue-js/pull/713
https://github.com/supabase/supabase-flutter/pull/530
=> feat(gotrue): add scope to signOut

Examples/Examples.xcodeproj/xcshareddata/xcschemes/UserManagement.xcscheme, Sources/GoTrue/GoTrueClient.swift, Sources/GoTrue/Internal/APIClient.swift, Sources/GoTrue/Types.swift, Tests/GoTrueTests/GoTrueClientTests.swift, Tests/GoTrueTests/Mocks/Mocks.swift, Tests/GoTrueTests/RequestsTests.swift
Fix https://github.com/supabase-community/supabase-swift/issues/176
When the user is deleted through Admin, the call to `signOut` on the client fails and the user doesn't log out locally because it returns a 404.
Ignore 404 and 401 errors when signing out, which will ensure to always log out the user locally.
=> fix(gotrue): ignore 401 and 404 errors on sign out

Sources/Supabase/SupabaseClient.swift, Sources/Supabase/Types.swift
Feature
When using `SupabaseClient`, developers cannot set the `encoder` and `decoder` used by PostgrestClient.
Add encoder and decoder parameters to SupabaseClientOptions.DatabaseOptions, this allows developers to pass in their own encoder and decoder
=> feat(postgrest): set coder in SupabaseClientOptions

Package.swift, Sources/PostgREST/PostgrestBuilder.swift, Sources/Supabase/Types.swift, Sources/_Helpers/Logger.swift
=> refactor: add debug logging

Sources/Auth/AuthClient.swift, Sources/Auth/Types.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testResendEmail.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testResendPhone.1.txt
Close #108 
User isn't able to resend email and mobile OTP.
Adds 2 methods:
```swift
func resend(
email: String,
type: ResendEmailType,
emailRedirectTo: URL? = nil,
captchaToken: String? = nil
) async throws
```
and 
```swift
func resend(
phone: String,
type: ResendMobileType,
captchaToken: String? = nil
) async throws -> ResendMobileResponse
```
=> feat(auth): add resend method

Sources/Auth/AuthClient.swift, Sources/Auth/AuthError.swift, Sources/Auth/Internal/Dependencies.swift, Sources/Auth/Types.swift, Tests/AuthTests/AuthResponseTests.swift, Tests/AuthTests/MockHelpers.swift, Tests/AuthTests/Mocks/Mocks.swift, Tests/AuthTests/RequestsTests.swift
=> docs(auth): improve docs for auth

Sources/PostgREST/PostgrestClient.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.query-non-default-schema.txt
Feature
PostgrestClient isn't able to dynamically switch the schema.
Add `schema(_:)` method for PostgrestClient, that returns a new client instance configured with the provided schema.
=> feat(postgrest): allow switching schema

Sources/Realtime/RealtimeChannel.swift
Feature
The user needs to manually call `realtime.connect()`
When calling `subscribe` on a channel, it automatically connects the socket if it isn't connected.
=> feat: auto-connect socket on channel subscription

.github/workflows/ci.yml
=> ci: update Xcode to 15.2

Examples/UserManagement/AuthView.swift, Examples/UserManagement/ProfileView.swift, Examples/UserManagement/Supabase.swift, Examples/UserManagement/supabase/.gitignore, Examples/UserManagement/supabase/config.toml, Examples/UserManagement/supabase/migrations/20240125111924_init.sql, Sources/Auth/AuthAdmin.swift, Sources/Auth/AuthClient.swift, Sources/Auth/Internal/APIClient.swift, Sources/Auth/Types.swift, Sources/PostgREST/Types.swift, Sources/Storage/TransformOptions.swift, Sources/Storage/Types.swift, Sources/_Helpers/Request.swift, Sources/_Helpers/SharedModels/PostgrestError.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testDeleteUser.1.txt
Close #192 
Missing implementation of Admin APIs
- Add `AuthAdmin` actor that will contain all admin endpoints
- Add `deleteUser` method for deleting a user using the `service_role` key
`service_role` key should never be exposed on client code, it will be up to the library user to make sure `service_role` key is safe.
=> feat: add AdminAPI and deleteUser method

Examples/UserManagement/ProfileView.swift, Examples/UserManagement/supabase/migrations/20240125111924_init.sql, Sources/Storage/StorageFileApi.swift
Docs update for https://github.com/supabase-community/supabase-swift/issues/227
=> docs: use user id when storing user's avatar image

.github/workflows/ci.yml, Sources/Realtime/V2/PostgresAction.swift, Sources/Realtime/V2/RealtimeChannelV2.swift
=> ci: add Swift 5.8 job

Sources/Auth/AuthClient.swift, Sources/Auth/Internal/EventEmitter.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/Mocks/MockEventEmitter.swift, Tests/AuthTests/Mocks/Mocks.swift, Tests/AuthTests/RequestsTests.swift
fix / refactor
Listening for auth change events is implemented only by Swift Async/Await, this has some inconsistencies, such as not emitting the `initialSession`.
Refactor implementation to use closure based listeners, and make async/await API use closure based internally
=> Improve EventEmitter implementation

Sources/Auth/AuthClient.swift, Sources/Auth/Internal/EventEmitter.swift, Sources/Auth/Internal/SessionManager.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/Mocks/MockEventEmitter.swift, Tests/AuthTests/Mocks/MockSessionManager.swift, Tests/AuthTests/Mocks/Mocks.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/SessionManagerTests.swift
=> refactor: simplify auth tests mocks

Sources/PostgREST/PostgrestFilterBuilder.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.test-or-filter-with-referenced-table.txt
Feature
When using the or filter, the columns have to be in the table referenced in the "from" clause
Users can now specify an optional "referencedTable" parameter to the or filter, allowing the or to reference other tables besides the main table in the "from" clause.
=> feat: Add optional "referencedTable" parameter to OR PostGREST filter

Sources/Auth/AuthClient.swift, Sources/Auth/AuthStateChangeListener.swift, Sources/Auth/Internal/EventEmitter.swift, Tests/AuthTests/AuthStateChangeListenerHandleTests.swift
=> feat: add AuthStateChangeListenerRegistration type

Examples/Examples/HomeView.swift, Sources/Auth/AuthClient.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testReauthenticate.1.txt, Tests/RealtimeTests/_PushTests.swift, supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved
Close https://github.com/supabase-community/supabase-swift/issues/130
=> feat: add reauthenticate method

Examples/Examples.xcodeproj/project.pbxproj, Examples/Examples/Auth/AuthView.swift, Examples/Examples/Auth/AuthWithEmailAndPassword.swift, Examples/Examples/ExamplesApp.swift, Examples/Examples/HomeView.swift, Examples/Examples/RootView.swift, Examples/Examples/Storage/BucketDetailView.swift, Examples/Examples/Storage/BucketList.swift, Examples/Examples/Storage/FileObjectDetailView.swift, Examples/Examples/Stringfy.swift, Examples/supabase/migrations/20221223094509_init.sql, Package.resolved, Package.swift, Sources/Storage/Bucket.swift, Sources/Storage/BucketOptions.swift, Sources/Storage/FileObject.swift, Sources/Storage/StorageError.swift, Sources/Storage/StorageFileApi.swift, Sources/Storage/StorageHTTPClient.swift, Sources/_Helpers/Request.swift, Tests/StorageTests/SupabaseStorageClient+Test.swift, Tests/StorageTests/SupabaseStorageTests.swift, supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved
Close https://github.com/supabase-community/supabase-swift/issues/146
=> feat(storage): add `createSignedURLs` method

Examples/Examples.xcodeproj/project.pbxproj, Examples/Examples/ActionState.swift, Examples/Examples/AnyJSONView.swift, Examples/Examples/HomeView.swift, Examples/Examples/Profile/ProfileView.swift, Examples/Examples/Profile/UserIdentityList.swift, Examples/Examples/Storage/BucketList.swift, Examples/supabase/config.toml, Sources/Auth/AuthClient.swift, Sources/Auth/Types.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/Resources/session.json, Tests/AuthTests/Resources/signup-response.json, Tests/AuthTests/Resources/user.json, Tests/AuthTests/__Snapshots__/RequestsTests/testUnlinkIdentity.1.txt, supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved
Close https://github.com/supabase-community/supabase-swift/issues/193
=> feat(auth): link identity

Sources/PostgREST/PostgrestTransformBuilder.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.select-after-an-insert.txt
Close https://github.com/supabase-community/supabase-swift/issues/207
=> feat(database): add select on query result

Sources/Auth/AuthClient.swift, Sources/Auth/Types.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testSignInWithEmailAndPassword.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testSignInWithPhoneAndPassword.1.txt
Close https://github.com/supabase-community/supabase-swift/issues/210
=> feat(auth): add captcha token to sign-in with password methods

Sources/Auth/AuthAdmin.swift, Sources/Auth/AuthClient.swift, Sources/Auth/AuthMFA.swift, Sources/Auth/Internal/APIClient.swift, Sources/Auth/Internal/CodeVerifierStorage.swift, Sources/Auth/Internal/Dependencies.swift, Sources/Auth/Internal/EventEmitter.swift, Sources/Auth/Internal/SessionManager.swift, Sources/Auth/Internal/SessionStorage.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/Mocks/MockAPIClient.swift, Tests/AuthTests/Mocks/MockEventEmitter.swift, Tests/AuthTests/Mocks/MockSessionManager.swift, Tests/AuthTests/Mocks/Mocks.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/SessionManagerTests.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift
=> refactor: simplify Auth dependency system

Sources/PostgREST/Deprecated.swift, Sources/PostgREST/PostgrestClient.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift
Close https://github.com/supabase-community/supabase-swift/issues/281
=> refactor: make PostgrestClient a class and not an actor

Sources/Realtime/V2/WebSocketClient.swift
Bug fix
When the WebSocket is closed by the client, the listener for messages doesn't stop.
By wrapping the web socket task in a SocketStream class that exposes a custom cancel method, we make sure to finish the stream when canceling the socket connection on the client side.
There are some caveats when wrapping WebSocket in async/await, but thanks to https://www.donnywals.com/iterating-over-web-socket-messages-with-async-await-in-swift/ this PR fixes it.
=> fix(realtime): web socket message listener doesn't stop

Sources/Auth/AuthClient.swift, Sources/Auth/Types.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testSignInWithSSOUsingDomain.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testSignInWithSSOUsingProviderId.1.txt
Close https://github.com/supabase-community/supabase-swift/issues/128
=> feat(auth): add `signInWithSSO` method

Sources/Auth/Internal/SessionStorage.swift, Sources/Auth/Types.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/MockHelpers.swift, Tests/AuthTests/Resources/stored-session_2_4_0.json, Tests/AuthTests/Resources/stored-session_2_5_0.json, Tests/AuthTests/StoredSessionTests.swift
=> fix(auth): stored session backwards compatibility

Sources/PostgREST/PostgrestBuilder.swift, Sources/_Helpers/Request.swift
Fixes a bug which could lead to a race condition when executing the request on Postgrest.
Lock was being acquired first for updating the fetchOptions and then inside the `execute` method for executing the request, this could lead to the `execute` method to use the wrong fetch options.
Move assignment of `fetchOptions` inside `execute` method, on a single lock acquisition.
=> fix(postgrest): race condition when setting fetchOptions and execute method call

.github/workflows/conventional-commits-lint.js, Sources/PostgREST/PostgrestClient.swift, Sources/Realtime/V2/CallbackManager.swift, Sources/Realtime/V2/WebSocketClient.swift, Sources/_Helpers/EventEmitter.swift, Tests/RealtimeTests/CallbackManagerTests.swift
LockIsolated values should be private to avoid misusage.
=> refactor: add private access control to lock isolated values

Sources/PostgREST/Deprecated.swift, Sources/PostgREST/PostgrestFilterBuilder.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Sources/Supabase/SupabaseClient.swift, Tests/RealtimeTests/_PushTests.swift
- expose `PostgrestClient` methods directly in `SupabaseClient` to follow other client libs behavior
- deprecate access to `SupabaseClient.database`
- deprecate `PostgrestFilterBuilder.textSearch(_:range:)`
=> feat: expose PostgrestClient methods directly in SupabaseClient

Examples/Examples/Profile/UserIdentityList.swift, Examples/supabase/config.toml, Sources/Auth/AuthClient.swift, Sources/Auth/Types.swift, Sources/_Helpers/Request.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testGetLinkIdentityURL.1.txt
- We had a `_getURLForLinkIdentity` experimental method for implementing manual identity linking.
- This PR drops the experimental flag, and rename the method to `getLinkIdentityURL` to be aligned with Flutter.
=> feat(auth): add `getLinkIdentityURL`

Sources/PostgREST/PostgrestFilterBuilder.swift, Sources/PostgREST/PostgrestTransformBuilder.swift, Sources/PostgREST/URLQueryRepresentable.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, Tests/PostgRESTTests/URLQueryRepresentableTests.swift, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.containedBy-using-array.txt, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.containedBy-using-json.txt, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.containedBy-using-range.txt, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.iLikeAllOf.txt, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.iLikeAnyOf.txt, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.likeAllOf.txt, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.likeAnyOf.txt
Add:
- geojson()
- explain()
- likeAllOf()
- likeAnyOf()
- iLikeAllOf()
- iLikeAnyOf()
=> feat(postgrest): add geojson, explain, and new filters

Sources/Functions/FunctionsClient.swift, Sources/Functions/Types.swift, Sources/Supabase/SupabaseClient.swift, Sources/Supabase/Types.swift, Tests/FunctionsTests/FunctionsClientTests.swift, Tests/SupabaseTests/SupabaseClientTests.swift
Add support for specifying function region when invoking function.
=> feat(functions): add support for specifying function region

Sources/Realtime/RealtimeChannel+AsyncAwait.swift, Sources/Realtime/V2/PushV2.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Sources/_Helpers/EventEmitter.swift, Tests/RealtimeTests/RealtimeTests.swift, Tests/_HelpersTests/ObservationTokenTests.swift
Add closure based methods for RealtimeChannel:
Library currently exposes only methods that returns an `AsyncStream` to be used in Swift Concurrency model.
This PR add closure based methods `onPostgresChange`, `onBroadcast`, and `onPresenceChange`
=> feat(realtime): add closure based methods

.github/workflows/auth.yml, .github/workflows/functions.yml, .github/workflows/postgrest.yml, .github/workflows/realtime.yml, .github/workflows/storage.yml, .github/workflows/supabase.yml, README.md, Sources/Auth/AuthClient.swift, Sources/Realtime/V2/WebSocketClient.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/RequestsTests.swift
- Fixes some issues building the library in Linux/Windows.
- Adds a **Supported Platforms** section to README making it clear the Linux/Windows aren't officially supported and may stop working on future versions.
See discussion in https://github.com/supabase/supabase-swift/pull/337
=> fix: linux build

Sources/Functions/FunctionsClient.swift, Sources/Supabase/SupabaseClient.swift
Close https://github.com/supabase/supabase-swift/issues/252
Add experimental method to invoke function with streamed responses
To implement the streamed responses, we need to set up a custom `URLSession` for setting its `delegate` property, which means that it doesn't use the `customFetch` that is provided to the `functions` package and all other `sub-packages`.
I prefer keeping it `Experimental` until we try to refactor the code so that all requests uses the same `URLSession` instance.
=> feat(functions): add experimental invoke with streamed responses

Sources/Storage/StorageFileApi.swift
Fixes https://github.com/supabase/supabase-swift/issues/351
`getSignedURLs` was using the default encoder which encodes keys as `snake_case` by default. But this endpoint requires `lowerCamelCase` keys.
=> fix(storage): getSignedURLs method using wrong encoder

Sources/Auth/AuthClient.swift, Tests/AuthTests/AuthClientTests.swift, Tests/IntegrationTests/AuthClientIntegrationTests.swift
Fix https://github.com/supabase/supabase-swift/issues/358
=> fix(auth): sign out should ignore 403s

Sources/Auth/AuthClient.swift, Sources/Auth/Internal/Helpers.swift, Tests/AuthTests/ExtractParamsTests.swift
Fix https://github.com/supabase/supabase-swift/issues/364
Params extraction logic was extracting only the fragment OR the query
Params extraction logic now extracts both from the fragment and query if both exist.
=> fix(auth): extract both query and fragment from URL

Sources/Functions/FunctionsClient.swift, Sources/Functions/Types.swift, Tests/FunctionsTests/FunctionsClientTests.swift
Fix https://github.com/supabase/supabase-swift/pull/346#discussion_r1592835376
Fix https://github.com/supabase/supabase-swift/issues/362
https://github.com/supabase/supabase-swift/pull/346 introduced a regression where it doesn't allow to invoke a function with a custom HTTP method anymore
=> fix(functions): invoke with custom http method

Sources/PostgREST/PostgrestClient.swift, Sources/_Helpers/SharedModels/HTTPError.swift
- Export error, so clients can catch it
- Add localized description for better print statements
=> Improve HTTP Error

Sources/Auth/AuthClient.swift
This PR gives the client the ability to get the session without validating it first. This can be useful to display user info while offline.
The changes in `SessionManager` are required, since before the `shouldValidateExpiration` parameter was ignored if a task is already running.
=> Export ability to get session without validation

Sources/Functions/FunctionsClient.swift, Sources/Functions/Types.swift, Sources/Storage/StorageFileApi.swift, Sources/_Helpers/SharedModels/HTTPError.swift, Tests/FunctionsTests/FunctionsClientTests.swift
Close https://github.com/supabase/supabase-swift/issues/255
=> feat(functions): invoke function with custom query params

Sources/Auth/AuthClient.swift
This lets the client reset the session, which is relevant if a logout fails (for example if the user is offline).
=> fix(auth): sign out regardless of request success

Sources/Auth/AuthClient.swift
The `updateUser` call was missing the `redirectTo` query item. I added the same way its used in other calls.
=> fix(auth): adds missing `redirectTo` query item to `updateUser`

Sources/Auth/AuthClient.swift, Sources/PostgREST/PostgrestFilterBuilder.swift, Tests/IntegrationTests/Potsgrest/PostgrestFilterTests.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift
Fix
Currently any type can be passed to the `is` filter.
Only `true`, `false`, or `nil` are allowed.
https://github.com/supabase/supabase-flutter/pull/920
=> fix(postgrest): update parameter of `is` filter to allow only `Bool` or `nil`

Sources/Auth/Internal/APIClient.swift
I noticed that auth calls like `updateUser` would fail due to a wrong JWT token. The cause for this was, that the `execute` method would override the `Authentication` header to the anon key. I changed the call, such that the `execute` method does not override existing headers.
=> fix(auth): header being overridden

Package.swift, Sources/Auth/AuthClient.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Sources/Realtime/V2/Types.swift, Sources/Realtime/V2/WebSocketClient.swift, Sources/Supabase/SupabaseClient.swift, Sources/Supabase/Types.swift, Sources/_Helpers/HTTP/HTTPHeader.swift, Tests/IntegrationTests/RealtimeIntegrationTests.swift, Tests/RealtimeTests/RealtimeTests.swift, Tests/RealtimeTests/_PushTests.swift, Tests/SupabaseTests/SupabaseClientTests.swift
Exposes public Realtime configuration options.
Realtime configuration options are public, but cannot be configured by the client.
Realtime configuration options can now be set by the client.
This is not ready to be merged. Tests need to be updated.
=> feat: expose Realtime options on SupabaseClient

Sources/Storage/StorageApi.swift
The same issue fixed in https://github.com/supabase/supabase-swift/pull/379 but for `storage`.
=> fix(storage): headers overridden

Sources/Supabase/Deprecated.swift, Sources/Supabase/SupabaseClient.swift
I wasn't able to reproduce it, but I have an assumption that these changes may fix the following crashes.
Fix https://github.com/supabase/supabase-swift/issues/239
Fix https://github.com/supabase/supabase-swift/issues/385
Inner clients from SupabaseClient were defined as `lazy var`, but `lazy var` isn't thread-safe in Swift, this was probably causing some crashes when accessed from different threads.
We also relied on it to mark the `SupabaseClient` class as `@unchecked Sendable`.
Moved inner clients to a `LockIsolated` and made `SupabaseClient` conform to `Sendable`.
=> fix: race condition when accessing SupabaseClient

Examples/Examples/Profile/UserIdentityList.swift, Sources/Auth/AuthClient.swift, Sources/Auth/Internal/Dependencies.swift, Sources/Auth/Internal/URLOpener.swift, Tests/AuthTests/AuthClientTests.swift, Tests/IntegrationTests/AuthClientIntegrationTests.swift
Feature
Link identity was implemented with `getLinkIdentityURL` which returned a URL that the developer should open externally.
Besides the behavior above, this PR adds a convenience `linkIdentity` method that automatically opens the URL externally.
=> feat(auth): add linkIdentity method

.github/workflows/auth.yml, .github/workflows/functions.yml, .github/workflows/postgrest.yml, .github/workflows/realtime.yml, .github/workflows/storage.yml, .github/workflows/supabase.yml, Sources/_Helpers/FoundationExtensions.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.filter-starting-with-non-alphanumeric.txt
Fix https://github.com/supabase/supabase-swift/issues/401
Can't include query values that contain any of the characters `:#[]@!$&'()*+,;=`, this had been fixed before, but got lost on some PRs ago.
Manually escape the query items, and don't use the default escaping logic from Foundation.
=> fix: manually percent encode query items to allow values with + sign

Sources/Auth/AuthClient.swift, Sources/Auth/AuthError.swift, Sources/Auth/Internal/Contants.swift, Sources/Auth/Internal/SessionManager.swift, Sources/Auth/Internal/SessionStorage.swift, Sources/Auth/Types.swift, Sources/_Helpers/AnyJSON/AnyJSON.swift, Tests/AuthTests/Mocks/Mocks.swift
Add convenience `isExpired` variable to session type, [mimics flutter behavior](https://github.com/supabase/supabase-flutter/blob/d5623522d964d101a72db483af2dfd7674b9ac74/packages/gotrue/lib/src/types/session.dart#L74)
=> feat(auth): add isExpired variable to session type

Sources/Storage/StorageFileApi.swift
`list` methods is sending a request to API storage with **snake_case** instead of **lowerCamelCase** for `SortBy` option
Using a regular encoder to send the correct key, so now the key `sortBy` sent works.
=> fix(storage): list method using wrong encoder

Sources/Storage/Helpers.swift, Sources/Storage/StorageFileApi.swift, Sources/Storage/Types.swift
Feature
Developer must specify the content-type manually
Use `UTType` from Apple framework for getting the MIME type based on a file extension, ie `.jpg -> image/jpeg`.
Note: not all file extensions are supported, so it defaults to `application/octet-stream`
=> feat(storage): fill content-type based on file extension

Sources/Realtime/V2/PushV2.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/_Helpers/Task+withTimeout.swift, Tests/RealtimeTests/RealtimeTests.swift, Tests/_HelpersTests/WithTimeoutTests.swift, supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fix
`channel.subscribe()` currently doesn't handle timeout, if for some reason channel doesn't receive a reply back, if blocks forever.
- `channel.subscribe()` retries the subscription in case of timeout.
- timeout is configured through Configuration object when initializing client.
I'll handle retry limits on a future PR, so it doesn't keep retrying forever.
=> fix(realtime): handle timeout when subscribing to channel

Examples/Examples/ExamplesApp.swift, Sources/Auth/AuthClient.swift, Sources/Auth/AuthClientConfiguration.swift, Sources/Auth/Defaults.swift, Sources/Auth/Internal/SessionManager.swift, Sources/Supabase/SupabaseClient.swift, Sources/Supabase/Types.swift, Tests/AuthTests/SessionManagerTests.swift, Tests/SupabaseTests/SupabaseClientTests.swift, Tests/_HelpersTests/WithTimeoutTests.swift
Close https://github.com/supabase/supabase-swift/issues/409
=> feat(auth): add options for disabling auto refresh token

Sources/Auth/Internal/SessionManager.swift, Sources/_Helpers/HTTP/LoggerInterceptor.swift, Sources/_Helpers/SupabaseLogger.swift, Sources/_Helpers/TaskLocalHelpers.swift
Adds more logs to the to token refresh logic for easier debugging.
=> feat: improve logging on token refresh logic

Sources/Auth/AuthClient.swift
See discussion: https://github.com/supabase/auth-js/pull/915
=> fix(auth): don't call removeSession prematurely

Sources/Auth/AuthClient.swift, Sources/Realtime/V2/PushV2.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Tests/IntegrationTests/RealtimeIntegrationTests.swift, Tests/RealtimeTests/RealtimeTests.swift, Tests/RealtimeTests/_PushTests.swift, Tests/SupabaseTests/SupabaseClientTests.swift
Make `RealtimeChannelV2` and `RealtimeClientV2` classes instead of actor, and add protect mutable state using a `LockIsolated`.
This makes the call side to not require to be on an async context.
```diff
- let channel = await client.channel("messages")
+ let channel = client.channel("messages")
```
Note this is not a breaking change, the compiler would only emit a warning stating that the `await` isn't required.
=> refactor(realtime): drop actor from RealtimeChannel and RealtimeClient

Sources/Auth/Defaults.swift, Sources/Helpers/SupabaseLogger.swift, Sources/PostgREST/Defaults.swift
This is part of the Swift 6 mode support, some concurrency warnings will become errors when Swift 6 is enabled.
This PR fixes a couple of concurrency warnings, by not using the `ISO8601DateFormatter`, which isn't `Sendable` in favor of the `DateFormatter`, which is `Sendable` and is already being used on some places
=> fix: concurrency warnings pre swift 6 support

Sources/Auth/AuthClientConfiguration.swift, Sources/Auth/Defaults.swift, Sources/Auth/Internal/SessionStorage.swift, Sources/Supabase/SupabaseClient.swift, Sources/Supabase/Types.swift, Tests/AuthTests/MockHelpers.swift, Tests/AuthTests/Resources/local-storage.json, Tests/AuthTests/StoredSessionTests.swift, Tests/SupabaseTests/SupabaseClientTests.swift
Bug fix
When using multiple projects, for example, a dev and a production, both environments shares the same token.
- Use project ref as a namespace when accessing stored token.
- Add support for providing a custom storage key to store the token on local storage.
=> fix(auth): use project ref as namespace for storing token

Sources/Auth/Defaults.swift, Sources/Helpers/AnyJSON/AnyJSON+Codable.swift, Sources/Helpers/DateFormatter.swift, Sources/Helpers/SupabaseLogger.swift, Sources/PostgREST/Defaults.swift, Tests/PostgRESTTests/JSONTests.swift, supabase-swift.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fix #434 
There was a breaking change on the `2.13.4` release, which broke the supported date formats to decode data from.
=> fix: date formatter breaking change

Sources/Supabase/SupabaseClient.swift
Fix #438 
When `initialSession` event occurs, access token isn't sent to realtime
Send accessToken also when `initialSession` event happens.
=> fix(realtime): send access token to realtime on initial session

Sources/Supabase/SupabaseClient.swift, Tests/SupabaseTests/SupabaseClientTests.swift
Expose SupabaseClient headers as requested in https://github.com/supabase/supabase-swift/issues/441#issuecomment-2211419514
=> fix: expose SupabaseClient headers

Examples/Examples/Profile/ProfileView.swift, Examples/Examples/Profile/UpdateProfileView.swift, Sources/Auth/AuthClient.swift, Sources/Auth/Types.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testVerifyOTPUsingTokenHash.1.txt
Fix https://github.com/supabase/supabase-swift/issues/446
`verifyOTP` using token hash method is missing from library but present on documentatino.
Add `verifyOTP` using token hash.
=> fix(auth): verify otp using token hash

Sources/Auth/AuthAdmin.swift, Sources/Auth/AuthClient.swift, Sources/Auth/AuthMFA.swift, Sources/Auth/Internal/APIClient.swift, Sources/Auth/Internal/Dependencies.swift, Sources/Auth/Internal/SessionManager.swift, Sources/Auth/Internal/SessionStorage.swift, Tests/AuthTests/AuthClientMultipleInstancesTests.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/MockHelpers.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/SessionManagerTests.swift, Tests/AuthTests/StoredSessionTests.swift, Tests/IntegrationTests/AuthClientIntegrationTests.swift
Close https://github.com/supabase/supabase-swift/issues/441
`Auth` uses a singleton dependency, so all client instances use the same set of dependencies, this makes it impossible to use multiple auth instances properly.
`AuthClient` has a unique identifier, now used to index an instance of the `Dependencies` struct. Each `AuthClient` has its own `Dependencies`.
=> feat(auth): add support for multiple auth instances

Sources/Auth/Internal/Keychain.swift, Tests/AuthTests/SessionManagerTests.swift
This PR aligns the behavior of KeychainLocalStorage on iOS and macOS. 
When one app save an item in KeychainLocalStorage with an access group on macOS, another app/extension with the same access group would not be able to access the item without the user having to enter their login keychain password. On iOS this would work without user having to enter any passwords.
Both on iOS and macOS apps/extensions are able to access keychain items with the shared access group correctly without the user having to enter their password.
=> fix(auth): prevent from requesting login keychain password os macOS

Sources/Auth/Types.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testUpdateUser.1.txt
=> fix(auth): add missing nonce param when updating user

Sources/Helpers/HTTP/HTTPRequest.swift, Sources/PostgREST/PostgrestQueryBuilder.swift, Sources/PostgREST/PostgrestTransformBuilder.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.select-after-bulk-upsert.txt
Bug fix
When chaining a `select` after a `upsert` call, the `prefer` header gets duplicated.
Avoid duplicated header fields
=> fix(postgrest): avoid duplicated columns and prefer fields

Examples/Examples.xcodeproj/project.pbxproj, Examples/SlackClone/AuthView.swift, Examples/SlackClone/Info.plist, Examples/SlackClone/SlackCloneApp.swift, Examples/SlackClone/Supabase.swift, Examples/SlackClone/supabase/config.toml, Sources/Realtime/V2/WebSocketClient.swift, Sources/Realtime/V2/WebSocketConnection.swift, Sources/TestHelpers/HTTPClientMock.swift, Tests/FunctionsTests/FunctionsClientTests.swift, Tests/RealtimeTests/MockWebSocketClient.swift
=> fix(realtime): crash when connecting socket

Tests/IntegrationTests/AuthClientIntegrationTests.swift
Test integration project doesn't require email confirmation anymore due send email limitation
=> test(integration): compare email instead of newEmail

.swiftpm/configuration/Package.resolved, .swiftpm/xcode/xcshareddata/xcschemes/Supabase.xcscheme, Package.swift, Sources/Realtime/RealtimeChannel.swift, Sources/Realtime/V2/PushV2.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Sources/Realtime/V2/Types.swift, Supabase.xcworkspace/xcshareddata/swiftpm/Package.resolved, TestPlans/AllTests.xctestplan, Tests/HelpersTests/AnyJSONTests.swift, Tests/IntegrationTests/RealtimeIntegrationTests.swift, Tests/RealtimeTests/RealtimeTests.swift, Tests/RealtimeTests/_PushTests.swift
Broadcast messages can be sent through HTTP without subscribing to channel.
=> feat(realtime): send broadcast events through HTTP

Package.swift, Sources/Supabase/SupabaseClient.swift, Sources/Supabase/Types.swift, Supabase.xcworkspace/xcshareddata/swiftpm/Package.resolved, Tests/SupabaseTests/SupabaseClientTests.swift
Adds support for the accessToken option on the Supabase client which can be used to provide a third-party authentication (e.g. Auth0, Clerk, Firebase Auth, ...) access token or ID token to be used instead of Supabase Auth.
When set, `supabase.auth.xyz` cannot be used and an error will be thrown.
See https://github.com/supabase/supabase-js/pull/1004 for more information.
=> feat: add third-party auth support

Sources/Auth/Types.swift, Tests/AuthTests/Resources/user.json
Fix #482 
`last_sign_in_at` field is marked as required but should be optional.
=> fix(auth): mark identities last_sign_in_at field as optional

Package.swift, Sources/Realtime/Push.swift, Sources/Realtime/RealtimeChannel.swift, Sources/Realtime/RealtimeClient.swift, Sources/Supabase/SupabaseClient.swift, Tests/IntegrationTests/RealtimeIntegrationTests.swift, Tests/RealtimeTests/RealtimeTests.swift, Tests/RealtimeTests/_PushTests.swift, Tests/SupabaseTests/SupabaseClientTests.swift
=> refactor(realtime)!: make realtime channel and client actors

Package.resolved, Sources/Auth/AuthMFA.swift, Sources/Auth/Deprecated.swift, Sources/Auth/Types.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testMFAChallenge.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testMFAChallengePhone.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testMFAEnrollLegacy.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testMFAEnrollPhone.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testMFAEnrollTotp.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testMFAUnenroll.1.txt, Tests/AuthTests/__Snapshots__/RequestsTests/testMFAVerify.1.txt
Adds support for MFA with Phone factor
- Enroll - now allows for enrollment of Phone Factors
- Challenge for Phone - now takes in a channel
- List Factors - now supports access of Phone factors
JS: https://github.com/supabase/auth-js/pull/932
=> feat(auth): add MFA phone

Sources/Auth/Internal/CodeVerifierStorage.swift, Sources/Auth/Internal/Dependencies.swift, Sources/Auth/Internal/EventEmitter.swift
Fix issue brought on https://github.com/supabase/supabase-swift/pull/445#discussion_r1714098710
When having multiple auth instances, the AuthStateChangeEventEmitter gets shared between auth instances
Each auth instance has its own AuthStateChangeEventEmitter instance
=> fix(auth): auth event emitter being shared among clients

Sources/PostgREST/PostgrestBuilder.swift, Tests/PostgRESTTests/PostgrestBuilderTests.swift
Close https://github.com/supabase/supabase-swift/issues/489
=> feat(postgrest): set header on a per call basis

Sources/Auth/Internal/SessionStorage.swift, Tests/AuthTests/Resources/local-storage.json
To make it possible to share sessions between Swift and Flutter, the session structured stored should match.
This PR migrates the stored session that was stored as:
```json
{
"session": <Session>,
"expiration_date": <Date>
}
```
to store it directly as:
```
<Session>
```
Which is the expected structure for Flutter.
https://github.com/supabase/auth/issues/1727
=> fix(auth): store session directly without wrapping in StoredSession type

Sources/PostgREST/URLQueryRepresentable.swift, Tests/PostgRESTTests/BuildURLRequestTests.swift, Tests/PostgRESTTests/__Snapshots__/BuildURLRequestTests/testBuildRequest.filter-using-Date.txt
When using filters on `Timestampz` typed columns, the `Date.now.description` declaration only works for users with time in 24-hour format and not for those using 12-hour one. 
This pull request makes using filters simpler and less error-prone when manipulating the `Date` type.
In order to use filters with `Date` type, we need to have a custom logic in order to make it works properly.
When using a filter, the `Date.now` (or `Date()`) works by the book without having to implement a custom logic.
If my change doesn't work on other Date/Time types, please let me know. I would be happy to make this works for everyone and every Date/Time type
=> feat(postgrest): use `Date` when filtering columns

Sources/Auth/Storage/AuthLocalStorage.swift, Sources/Auth/Storage/KeychainLocalStorage.swift, Sources/Auth/Storage/WinCredLocalStorage.swift
When one needs to provide a custom instance of `KeychainLocalStorage` just to pass in an `access group`, one most pass in also the `service` value, usually you don't care about `service` value and wants to just use the default one.
Add a default value to the `service` param, so one can pass just an `access group` and keep the default `service` value.
https://github.com/supabase/supabase-swift/issues/516#issuecomment-2324533015
=> fix(auth): expose KeychainLocalStorage with default init params

Sources/Functions/FunctionsClient.swift
Fix https://github.com/supabase/supabase-swift/issues/523
=> fix(functions): fix streamed responses

.github/workflows/auth.yml, .github/workflows/functions.yml, .github/workflows/integration-tests.yml, .github/workflows/postgrest.yml, .github/workflows/realtime.yml, .github/workflows/storage.yml, .github/workflows/supabase.yml
- Add Xcode 16 to CI
- Remove Swift 5.9 from Linux job
=> ci: add Xcode 16

Package.swift, Sources/Realtime/PhoenixTransport.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Tests/RealtimeTests/RealtimeChannelTests.swift
Add a missing overload of the `onPostgresChange` method for listening for all changes.
=> fix(realtime): add missing `onPostgresChange` overload

Sources/Auth/AuthAdmin.swift, Sources/Auth/Types.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/Resources/list-users-response.json, Tests/IntegrationTests/AuthClientIntegrationTests.swift
Close https://github.com/supabase/supabase-swift/issues/529
Add `listUsers` admin method.
=> feat(auth): add listUsers admin method

Package.resolved, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Sources/Realtime/V2/Types.swift
=> fix(realtime): add RealtimeSubscription and deprecate Subscription

Examples/Examples.xcodeproj/project.pbxproj, Examples/Examples/Auth/AuthController.swift, Examples/Examples/Auth/AuthWithEmailAndPassword.swift, Examples/Examples/Contants.swift, Examples/Examples/HomeView.swift, Examples/Examples/Profile/ResetPasswordView.swift, Examples/Examples/Profile/UpdateProfileView.swift, Examples/supabase/config.toml, Sources/Auth/AuthClient.swift, Sources/Auth/Internal/EventEmitter.swift, Sources/Helpers/HTTP/LoggerInterceptor.swift
=> chore(docs): add password recovery example

Sources/Helpers/SupabaseLogger.swift, Sources/Helpers/TaskLocalHelpers.swift
=> fix: Swift 6 warnings related to `@_unsafeInheritExecutor` attribute

Sources/Realtime/Deprecated.swift, Sources/Realtime/RealtimeChannel+AsyncAwait.swift, Sources/Realtime/V2/PostgresAction.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Sources/Realtime/V2/RealtimeJoinConfig.swift, Sources/Realtime/V2/Types.swift, Tests/RealtimeTests/RealtimeChannelTests.swift, Tests/RealtimeTests/RealtimeTests.swift
=> refactor(realtime): general improvements

Examples/SlackClone/AppView.swift, Examples/SlackClone/AuthView.swift, Examples/SlackClone/ChannelListView.swift, Examples/SlackClone/ChannelStore.swift, Examples/SlackClone/Dependencies.swift, Examples/SlackClone/Logger.swift, Examples/SlackClone/MessageStore.swift, Examples/SlackClone/MessagesView.swift, Examples/SlackClone/Supabase.swift, Examples/SlackClone/UserStore.swift, Examples/SlackClone/supabase/config.toml, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Sources/Realtime/V2/RealtimeJoinConfig.swift
- Clean up SlackClone example
- Deprecate `updateAuth(jwt:)` from `RealtimeChannelV2`, use `setAuth` from `RealtimeClientV2` instead.
- Allow to clear token when `setAuth` is  called with `nil` value.
=> chore(docs): cleanup SlackClone example

.github/workflows/ci.yml, Examples/Examples.xcodeproj/project.pbxproj, Examples/Examples/ExamplesApp.swift, Examples/Examples/Supabase.plist, Examples/Examples/SupabaseConfig.swift, Examples/Examples/_Secrets.swift, Makefile
=> chore: simplify ci

Sources/Auth/Internal/Keychain.swift
Revert: https://github.com/supabase/supabase-swift/pull/455
Fix https://github.com/supabase/supabase-swift/issues/516
The addition on `kSecUseDataProtectionKeychain` broke when using on macOS so I decided to revert the change until I can better research about this.
=> fix: remove kSecUseDataProtectionKeychain

.github/workflows/ci.yml, Makefile, Sources/Auth/AuthClient.swift, Sources/Storage/StorageFileApi.swift, Tests/StorageTests/SupabaseStorageTests.swift
fix https://github.com/supabase/supabase-swift/issues/571
Mark `observeAppLifecycleChanges()` method with `@MainActor`
=> fix: build for Swift 5.9

Sources/Realtime/RealtimeChannel+AsyncAwait.swift, Sources/Realtime/V2/CallbackManager.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeMessageV2.swift, Tests/RealtimeTests/CallbackManagerTests.swift, Tests/RealtimeTests/RealtimeChannelTests.swift, Tests/RealtimeTests/RealtimeMessageV2Tests.swift
Add methods for listening for `system` event.
=> feat(realtime): add `system` event

Sources/Auth/AuthClient.swift, Tests/AuthTests/AuthClientTests.swift
Fix https://github.com/supabase/supabase-swift/issues/591
Error was using a fixed message instead of getting it from the `error_description` URL param.
Get the error from `error_description` param instead.
=> fix(auth): incorrect error when error occurs during PKCE flow

Sources/Auth/AuthError.swift
Updates the error codes to be in sync with the ones returned in https://github.com/supabase/auth/blob/master/internal/api/errorcodes.go
Reference: https://github.com/supabase/auth-js/pull/979
=> feat(auth): add new error codes

.github/workflows/ci.yml, .github/workflows/integration-tests.yml
=> ci: fix Xcode 16 version

Sources/Auth/Internal/SessionManager.swift
Fixes the issue described in https://github.com/supabase/supabase-swift/issues/596
- Only strictly `URLError` are retried or any error that directly conforms to `RetryableError`
- Any `NSError` or `Error` that conforms to `URLError` and is retryable will be retried along with any error that directly conforms to `RetryableError`
=> fix(auth): `URLError` coercion for `RetryableError` causing session to be deleted

Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Sources/Realtime/V2/Types.swift, Sources/Supabase/SupabaseClient.swift, Tests/RealtimeTests/RealtimeTests.swift
Adds a new `accessToken` closure to Realtime initialization options for pulling a valid access token when needed.
https://github.com/supabase/realtime-js/pull/439
https://github.com/supabase/supabase-js/pull/1320
=> feat(realtime): pull access token mechanism

Sources/Auth/AuthClient.swift, Sources/Auth/Types.swift, Tests/AuthTests/RequestsTests.swift, Tests/AuthTests/__Snapshots__/RequestsTests/testSignUpWithPhoneAndPassword.1.txt
Fix https://github.com/supabase/supabase-swift/issues/624
=> fix(auth): add missing channel param to signUp method

Package.swift, Sources/Helpers/AsyncValueSubject.swift, Sources/Helpers/Task+withTimeout.swift, Sources/Helpers/_Clock.swift, Sources/Realtime/V2/RealtimeChannelV2.swift, Sources/Realtime/V2/RealtimeClientV2.swift, Supabase.xcworkspace/xcshareddata/swiftpm/Package.resolved, Tests/IntegrationTests/RealtimeIntegrationTests.swift, Tests/RealtimeTests/RealtimeTests.swift, Tests/RealtimeTests/_PushTests.swift
refactor
Current code uses `Task.sleep` for waiting for time to pass, this isn't ideal when testing, since in tests we need to actually wait for time to pass.
Example, for testing a code that has a `Task.sleep(nanoseconds: NSEC_PER_SEC * 10)`, we need to actually wait for 10 seconds in test, which make tests take longer than it should.
Latest Swift offers a new protocol named `Clock` which solves this issue since there is a `TestClock` implementation which can be used on tests to "fake time to pass", unfortunately `Clock` is available only on newer OS versions, and Supabase support older platform for now.
So in this PR I had to add an intermediate `_Clock` protocol to make it possible to use `Clock` when available and fallback to the old `Task.sleep` on old platforms. This works fine …
=> refactor: use Clock protocol when available

Sources/Realtime/V2/Types.swift, Sources/Supabase/SupabaseClient.swift, Sources/Supabase/Types.swift
fix
Currently `nil` cannot be returned from `accessToken` function.
`nil` can be returned from `accessToken` when the user on the third-party auth is not signed in.
https://github.com/supabase/supabase-js/pull/1332
=> fix: make the return value of accessToken nullable

README.md
The code snippet in README.md gave me the error "product 'Supabase' required by package '<package>' target '<target>' not found. Did you mean '.product(name: "Supabase", package: "supabase-swift")'?". Applying the suggested fix worked, so I thought I'd update the README to do this directly :)
When just declaring Supabase as a dependency, Xcode fails to find the relevant package.
With this change, Xcode can properly find the Supabase package.
=> chore: fix Swift Package Manager dependency instruction

.swiftpm/xcode/xcshareddata/xcschemes/Auth.xcscheme, Sources/Auth/AuthClient.swift, Sources/Auth/AuthMFA.swift, Sources/Auth/Internal/Dependencies.swift, Sources/Auth/Internal/PKCE.swift, Tests/AuthTests/AuthClientMultipleInstancesTests.swift, Tests/AuthTests/AuthClientTests.swift, Tests/AuthTests/AuthErrorTests.swift, Tests/AuthTests/ExtractParamsTests.swift, Tests/AuthTests/PKCETests.swift, Tests/AuthTests/StoredSessionTests.swift, scripts/generate-coverage.sh
=> test(auth): increase code coverage

.swiftpm/xcode/xcshareddata/xcschemes/Storage.xcscheme, Package.swift, Sources/Helpers/Codable.swift, Sources/Helpers/HTTP/HTTPFields.swift, Sources/Storage/Codable.swift, Sources/Storage/Deprecated.swift, Sources/Storage/Helpers.swift, Sources/Storage/StorageApi.swift, Sources/Storage/StorageError.swift, Sources/Storage/StorageFileApi.swift, Tests/StorageTests/BucketOptionsTests.swift, Tests/StorageTests/FileOptionsTests.swift, Tests/StorageTests/Fixtures/file.txt, Tests/StorageTests/MultipartFormDataTests.swift, Tests/StorageTests/StorageBucketAPITests.swift, Tests/StorageTests/StorageErrorTests.swift, Tests/StorageTests/StorageFileAPITests.swift, Tests/StorageTests/TransformOptionsTests.swift, Tests/StorageTests/__Snapshots__/StorageBucketAPITests/StorageBucketAPITests-testCreateBucket.1.txt
This pull request includes multiple changes to improve code functionality, enhance test coverage, and update dependencies. The most important changes include enabling code coverage in the Xcode scheme, adding new helper methods and extensions, updating the `StorageFileApi` class, and adding new test cases.
* [`.swiftpm/xcode/xcshareddata/xcschemes/Storage.xcscheme`](diffhunk://#diff-8897d86c8839d937e0592123176437149aa6a6d7ccf456ab35ff7681402d8139L4-R4): Enabled code coverage and added `StorageTests` as a testable reference. [[1]](diffhunk://#diff-8897d86c8839d937e0592123176437149aa6a6d7ccf456ab35ff7681402d8139L4-R4) [[2]](diffhunk://#diff-8897d86c8839d937e0592123176437149aa6a6d7ccf456ab35ff7681402d8139L29-R51)
* [`Sources/Helpers/Codable.swift`](diffhunk://#diff-034749198a11163105aaa028941 …
=> test(storage): increase code coverage

.swiftpm/xcode/xcshareddata/xcschemes/PostgREST.xcscheme, Sources/PostgREST/Deprecated.swift, Sources/PostgREST/PostgrestBuilder.swift, Sources/PostgREST/PostgrestFilterBuilder.swift, Sources/PostgREST/PostgrestTransformBuilder.swift, Sources/PostgREST/URLQueryRepresentable.swift, Tests/PostgRESTTests/PostgresQueryTests.swift, Tests/PostgRESTTests/PostgrestBuilderTests.swift, Tests/PostgRESTTests/PostgrestFilterBuilderTests.swift, Tests/PostgRESTTests/PostgrestQueryBuilderTests.swift, Tests/PostgRESTTests/PostgrestRpcBuilderTests.swift, Tests/PostgRESTTests/PostgrestTransformBuilderTests.swift, Tests/PostgRESTTests/URLQueryRepresentableTests.swift
This pull request includes several updates to the `PostgREST` library, focusing on simplifying header and query management, improving JSON serialization, and adding comprehensive test coverage.
* [`Sources/PostgREST/PostgrestBuilder.swift`](diffhunk://#diff-f4db5930899552dc610d7efa6dda1c392c89047a132f6bd5a259b467d8a94c0fL109-R109): Simplified the logic for appending or updating the `prefer` header by introducing the `appendOrUpdate` method.
* [`Sources/PostgREST/PostgrestTransformBuilder.swift`](diffhunk://#diff-abb203efb96a9e057c32cc7d79f3e0dee3dbaf607122c88c3cfefafc3c999e91L26-R26): Refactored multiple methods to use the `appendOrUpdate` method for headers and query items, reducing code duplication and improving readability. [[1]](diffhunk://#diff-abb203efb96a9e057c32cc7d79f3e0dee3dbaf60 …
=> test(postgrest): increase code coverage

Sources/Auth/AuthClient.swift, Sources/Auth/Internal/Dependencies.swift, Sources/Helpers/SupabaseLogger.swift
This pull request introduces several changes to enhance logging capabilities and refactor the `AuthClient` class. The most important changes include modifying the `AuthClientID` type, adding a logger decorator, and updating the `Dependencies` structure to include a logger.
Enhancements to logging:
* [`Sources/Auth/AuthClient.swift`](diffhunk://#diff-5cb42ddf0c4428eaab423fe95ea140b1e0aeaf07f29d0beab53a1a711eb2abd0L17-R32): Changed `AuthClientID` type from `UUID` to `Int` and added `AuthClientLoggerDecorator` to include `client_id` in log messages.
* [`Sources/Helpers/SupabaseLogger.swift`](diffhunk://#diff-60e6e568eaef939f90aef284769b2cb06b9a9df9f99a059ebd80bfb230e79247L34-R34): Made `additionalContext` mutable in `SupabaseLogMessage` to allow modification of log messages.
Refactoring …
=> refactor(auth): change `AuthClientID` to `Int` to better visiblity of client usage

.swiftpm/xcode/xcshareddata/xcschemes/Realtime.xcscheme, Sources/Realtime/RealtimeChannelV2.swift, Sources/Realtime/RealtimeClientV2.swift, Sources/Realtime/RealtimeJoinConfig.swift, Tests/RealtimeTests/RealtimeTests.swift
Also:
- Call `setAuth` after heartbeat
- Send `x-client-info` when joining channel
=> fix(realtime): remove jwt check

Sources/Auth/AuthClient.swift, Sources/Auth/AuthClientConfiguration.swift, Sources/Auth/Deprecated.swift, Sources/TestHelpers/MockExtensions.swift
This pull request includes significant changes to the `AuthClient` class in `Sources/Auth/AuthClient.swift` to improve concurrency handling and integrate Combine for handling app lifecycle changes.
* Changed `AuthClient` from a `final class` to an `actor` to leverage Swift's concurrency model.
To keep backward compatibility, had to mark a few properties and methods of `AuthClient` as `nonisolated`, the `nonisolated` mark, shall be removed on a next major release.
Because of the change from class to actor, I had to change the way we observe the notification center.
* Added `Combine` import conditionally based on availability.
* Refactored `observeAppLifecycleChanges` to use Combine publishers for handling app lifecycle notifications.
These changes improve the concurrency model of …
=> fix(auth): make AuthClient an Actor

Sources/Realtime/RealtimeClientV2.swift, Sources/Realtime/Types.swift, Sources/TestHelpers/MockExtensions.swift, Supabase.xcworkspace/xcshareddata/swiftpm/Package.resolved, Tests/RealtimeTests/RealtimeTests.swift, Tests/RealtimeTests/_PushTests.swift
=> fix(realtime): Set default heartbeat interval to 25s

Sources/Auth/AuthClient.swift
Fix https://github.com/supabase/supabase-swift/issues/683
=> fix(auth): add missing @MainActor

Sources/Helpers/AsyncValueSubject.swift, Tests/HelpersTests/AsyncValueSubjectTests.swift
=> test: add tests for `AsyncValueSubject` type

Sources/Auth/AuthClient.swift
Just a docs update
Wrong error type
Correct error type
The old error type is deprecated - the new one works now.
=> fix: update outdated error doc

Sources/Realtime/RealtimeClientV2.swift, Sources/Realtime/Types.swift, Tests/RealtimeTests/RealtimeTests.swift
=> feat(realtime): add heartbeat callback

Package.swift, Sources/Helpers/Version.swift, Sources/Supabase/Constants.swift, Sources/Supabase/SupabaseClient.swift, Tests/SupabaseTests/SupabaseClientTests.swift
=> feat: add standard client headers

Sources/Functions/FunctionsClient.swift, Sources/Helpers/HTTP/HTTPRequest.swift
Bug fix
Close https://github.com/supabase/supabase-swift/issues/727
No request timeout defined, which uses default `URLSession` timeout which is 60 seconds.
Allow to specify a custom value for timeout a per-request basis, (internally, not configurable by the user)
Set all invoke functions requests timeout to 150 seconds
https://supabase.com/docs/guides/functions/limits
=> fix(functions): set request timeout to 150 seconds when invoking functions

Sources/Realtime/CallbackManager.swift, Tests/RealtimeTests/CallbackManagerTests.swift
Bug fix
Using "*" as event arg e.g. `onBroadcast(event: "*")` won't work. The callback is never triggered because the event never matched.
```swift
let subscription = = channel.onBroadcast(event: "*") { message in
print("new message:", message) // This never gets logged
}
```
I found it because I thought I had a bug in my app code, but once I enabled global logging, I got the log from `RealtimeClientV2.onMessage` which means the event was actually sent and received, but the callback isn't triggered.
Using "*" as event arg should work now.
The behavior is documented [here](https://supabase.com/docs/guides/realtime/broadcast?queryGroups=language&language=swift#receiving-broadcast-messages). It's also the same behavior (ie. treating "*" as wildcard) in other languages.
=> fix(realtime): wildcard event not handled in onBroadcast callback

Sources/Helpers/Logger/OSLogSupabaseLogger.swift, Sources/Helpers/Logger/SupabaseLogger.swift
Improvement
User needs to manually implement a `SupabaseLogger` which uses a `OSLog`.
We now provide a `SupabaseLogger` implementation that uses `OSLog`, since this is probably the most used logger across Apple projects.
=> feat: add OSLogSupabaseLogger type

Examples/Examples.xcodeproj/project.pbxproj, Examples/Examples/Auth/AuthView.swift, Examples/Examples/Auth/SignInWithFacebook.swift, Examples/Examples/ExamplesApp.swift, Examples/Examples/Info.plist, Examples/README.md, Supabase.xcworkspace/xcshareddata/swiftpm/Package.resolved
Add a new example on how to integrate Facebook SDK with the `signInWithIdToken` method.
=> chore: add Facebook Auth example

Sources/Auth/Internal/APIClient.swift, Tests/AuthTests/AuthClientTests.swift
Bug fix
Considering the scenario where a user is logged on both web and mobile using the Swift SDK, when the user signs out from the web using global scope, all sessions are removed from the auth service, including the session from the mobile app.
Any authenticated call made by the Swift SDK after that will throw an error and get it stuck in a state where it says it is signed in, but the session isn't accepted by the server.
Once the SDK gets a `session_not_found` or `refresh_token_not_found` error returned by the auth service, the SDK removes the session from storage and triggers a `SIGNED_OUT` event, cleaning up state.
=> fix(auth): remove session when it has been revoked
